### ISSUE TITLE
sqs list queues always fails with SignatureDoesNotMatch

### ISSUE THREAD

**Issue by lrascao** [gleber/erlcloud#113]
master branch
receive_message however works well

snippet:
ok = ssl:start(),
ok = erlcloud:start(),
ok = erlcloud_sqs:configure(AwsAccessKey, AwsSecretKey, AwsHost),
Queues = try erlcloud_sqs:list_queues()
			catch Exception:Error -> io:format("exception: ~p, error: ~p~n", [Exception, Error]), []
			end.

http_error,403,"Forbidden",
                                 <<"<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><Error><Type>Sender</Type><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message><Detail/></Error><RequestId>b8262869-972d-5988-8342-64ce5cf34645</RequestId></ErrorResponse>">>}}

**Comment by rawn** [comment]
This should probably be reopened again, as this fix broke erlcloud_s3:list_multipart_uploads/* and erlcloud_s3:abort_multipart/*.

If i revert just this fix, these calls stat working again.

It seems Amazon aren't consistent with how they calculate their signature over different services.

**Comment by lrascao** [comment]
i'm seeing the error, but what's weird is that i revert my change i keep seeing it, i'm using us-west-2 region, are you using the same?

**Comment by lrascao** [comment]
found the reason, S3 is signing a string containing the full S3 host, the string erlcloud is signing only contains the relative path, eg:
  aws is signing /s3.us-west-3.amazonaws.com
  erlcloud is signing /

**Comment by lrascao** [comment]
will issue a PR shortly fixing the issue above and the original reported here.
original fix will remain in place since S3 seems to be the special case, will create a private make_query_string method in S3 that will eventually be dropped when code is migrated to V4

**Comment by rawn** [comment]
Aha, ok, that explains thing. I have an ugly fix in place, since we needed to move on with this rather quickly, but i'll be happy to trade it in for a proper fix.

Good job and sorry I haven't answered for a while. We are using mainly eu-west-1 (ireland).

**Comment by lrascao** [comment]
Thanks, can you test my branch and check that it effectively solves the issue you detected? Will probably help in getting the merge done faster
