### ISSUE TITLE
Support BOOL columns in dynamodb

### ISSUE THREAD

**Issue by jni-** [gleber/erlcloud#123]
Hi, 

DynamoDB lets persist a "row" with "BOOL" as a type, like so : 

```json
{
  "enabled": {
    "BOOL": true
  }
}
```

But when retrieving it with erlcloud (with a scan), it fails : 

    (erlcloud) src/erlcloud_ddb2.erl:469: :erlcloud_ddb2.undynamize_value({"BOOL", true}, [])
    (erlcloud) src/erlcloud_ddb2.erl:484: :erlcloud_ddb2.undynamize_attr/2
    (erlcloud) src/erlcloud_ddb2.erl:492: :erlcloud_ddb2."-undynamize_object/3-lc$^0/1-0-"/3
    (erlcloud) src/erlcloud_ddb2.erl:492: :erlcloud_ddb2."-undynamize_object/3-lc$^0/1-0-"/3
    (erlcloud) src/erlcloud_ddb2.erl:1704: :erlcloud_ddb2."-scan_record/0-lc$^0/1-0-"/2
    (erlcloud) src/erlcloud_ddb2.erl:558: :erlcloud_ddb2.undynamize_folder/4
    (stdlib) lists.erl:1261: :lists.foldl/3
    (erlcloud) src/erlcloud_ddb2.erl:682: :erlcloud_ddb2.out/3

Not sure if I'm using it wrong or not though :) It could be that. 

I don't really have time to create a pull request for now (plus I'm sure I'd miss a couple of places to edit), but I might give it a go next week if it'd be a good addition!

Thanks

**Comment by stocks29** [comment]
+1

**Comment by ransomr** [comment]
New DynamoDB support is in
