### ISSUE TITLE
Problem creating table when using erlcloud_ddb2:configure/3

### ISSUE THREAD

**Issue by jhw** [gleber/erlcloud#153]
Hi,

I'm able to create a ddb2 table fine when I use configure/2, but when I add a specific region and use configure/3 I get the following:

{error,{http_error,400,"Bad Request",
                   <<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidHttpRequest</Code><Message>The HTTP request is invalid. Reason: Unable to parse request</Message></Error></Errors><RequestID>a97d3fa3-a837-4eef-94be-291fee27de75</RequestID></Response>">>}}

Just to be clear, configure/3 returns 'ok'; it's the subsequent create_table request which returns the HTTP error.

Many thanks.

----------------------------------------------------------------------------------------------

-module(ddb2_create_table_ireland).

-export([test/1]).

-define(HOSTNAME, "ec2.eu-west-1.amazonaws.com").

test([AWSKey, AWSSecretKey]) ->
    ssl:start(),
    erlcloud:start(),
    %% ok=erlcloud_ddb2:configure(AWSKey, AWSSecretKey) %% WORKS :-)
    ok=erlcloud_ddb2:configure(AWSKey, AWSSecretKey, ?HOSTNAME), %% DOESN'T WORK :-(
    Resp=erlcloud_ddb2:create_table(
	   <<"Thread">>,
	   [{<<"ForumName">>, s},
	    {<<"Subject">>, s},
	    {<<"LastPostDateTime">>, s}],
	   {<<"ForumName">>, <<"Subject">>},
	   5, 
	   5,
	   [{local_secondary_indexes,
	     [{<<"LastPostIndex">>, <<"LastPostDateTime">>, keys_only}]},
	    {global_secondary_indexes, [
					{<<"SubjectTimeIndex">>, {<<"Subject">>, <<"LastPostDateTime">>}, all, 10, 10}
				       ]}
	   ]),
    io:format("~p~n", [Resp]).

**Comment by ransomr** [comment]
Looks like you are trying to make ddb requests to ec2. Try "dynamodb.eu-west-1.amazonaws.com"

**Comment by jhw** [comment]
That's great; thank you very much.
