### ISSUE TITLE
Does ErlCloud supports "ExpressionAttributeValues" syntax?

### ISSUE THREAD

**Issue by posilva** [gleber/erlcloud#159]
Hi ,

first of all, thanks for you great job with erlcloud. I would like to know if erlcloud already supports ExpressionAttributeValues and UpdateExpression in the erlcloud_ddb2? 

Cheers

Pedro

**Comment by ransomr** [comment]
No, it does not. There is no support for a number of the newer features in DynamoDB. As far as I know no one is working on it. I'd welcome a PR if you'd like to do it. Thanks.

**Comment by smilerlee** [comment]
I'm on it, but the progress may be slow ... 😄

**Comment by ransomr** [comment]
This is now complete.
