### ISSUE TITLE
Question: records vs proplists

### ISSUE THREAD

**Issue by motobob** [gleber/erlcloud#162]
Hello @ransomr,

In a near future i'm going to PR https://github.com/gleber/erlcloud/compare/master...alertlogic:master
where a lot of functionality will be added and continue to be added (full sigV4 is coming just after) and we have a tine question on how records/proplists are currently used throughout erlcloud APIs returns.
Currently there is a messy mix of both. Are there any regulation already on this? 
We are thinking to generalize all that to common API all based on records and add new apis (e.g. RDS) using only records.

Are you okay with the approach?
Thanks.

**Comment by ransomr** [comment]
Yes. I prefer records for new APIs. Please don't change existing APIs though as it would break existing clients. Looking forward to the new functionality.

**Comment by motobob** [comment]
sure. existing apis will be left for backward compatability
