### ISSUE TITLE
[DynamoDB] Query API: KeyConditions became an optional parameter

### ISSUE THREAD

**Issue by smilerlee** [gleber/erlcloud#163]
I'm planing to update the implementation to catch up the DynamoDB's latest changes.

In our implementation of _Query_ API, it takes _KeyConditions_ as a required parameter.

As the document in source code noted:
> Required parameters are passed as function arguments. In addition
> all methods take an options proplist argument which can be used to
> pass optional parameters. See function documentation for examples.

However, since the latest release \(see [Document History for DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DocumentHistory.html)\), due to the new _KeyConditionExpression_ parameter of the _Query_ API, the _KeyConditions_ parameter became __optional__ and __legacy__.

_KeyConditionExpression_ and _KeyConditions_ are either-or choices, and someone may prefer the newer one.

So..., here comes the problem...

How should I do to make it (the _KeyConditions_) an optional parameter, but without breaking the backward compatibility?

How about adding a new function called _q2_? It seems awkward however...

Welcome to discuss!

**Comment by ransomr** [comment]
I would determine whether the input is KeyConditionExpression or KeyConditions based on the input type. KeyConditions must be a tuple or list of tuple. Presumably KeyConditionExpression will be binary or iolist, so I don't think there will be any ambiguity.

Additionally, you might want to consider a way to specify KeyConditionExpressions that simplify the process of specifying that and the corresponding ExpressionAttributeNames. That could make query much easier to use then having to always specify ExpressionAttributeNames. If you do that, you could just make sure that whatever form that input takes can be differentiated from KeyConditions.

**Comment by smilerlee** [comment]
Sorry for the late reply.

All new features have been implemented by now, include:
* New data types: BOOL, NULL, L, M
* Expressions: Projection, Condition, KeyCondition, Filter, Update (only binaries are supported currently)
* ExpressionAttributeNames and ExpressionAttributeValues
* Global Secondary Index online creation and deletion
* Scan on index
* And also some other new features

I'll test and review it carefully and make a PR several days later.

As to the new data types:
* Input of BOOL value is `{bool, true}` or `{bool, false}`
* Input of NULL value is `{null, true}`
* Untyped output of BOOL value is `true` or `false`
* Untyped output of NULL value is `undefined` (not `null`, using `undefined` is more reasonable in Erlang)

How do you think about these two types? Got any better idea?

**Comment by ransomr** [comment]
That sounds reasonable. Thanks for implementing this - looking forward to the PR.

**Comment by smilerlee** [comment]
Thanks for taking the PR.
