### ISSUE TITLE
[DynamoDB] How about remove atom value

### ISSUE THREAD

**Issue by smilerlee** [gleber/erlcloud#164]
From this commit:
[Add atom to dynamize_value](https://github.com/gleber/erlcloud/commit/02054ee5f03b81dee273213ef0712a38c2535fe0)

It makes the atoms available for input attribute values, that sounds awesome.

However, it also brings some ambiguities:
```
-type in_expected_item() :: {attr_name(), false} | condition().
-type condition() :: {attr_name(), not_null | null} |
                     {attr_name(), in_attr_value()} |
                     {attr_name(), in_attr_value(), comparison_op()} |
                     {attr_name(), {in_attr_value(), in_attr_value()}, between} |
                     {attr_name(), [in_attr_value(),...], in}.
```
We have special values `false`, `not_null` and `null` here, which mixed with `in_attr_value()`.

* In the case of condition, they're special value: not exists, not null (equals exists), null (equals not exists).
* In the case of input item, they're string value: `{"S": "false"}`, `{"S": "not_null"}` and `{"S": "null"}`.

But its not the end yet.

As we all know, in Erlang record, default value of non-specified property is `undefined`.
We could put the `undefined` value as `{"S": "undefined"}` into database by mistake so easily.

I suppose we should take this into consideration.

**Comment by ransomr** [comment]
Good catch - I wish I had thought of that before accepting the commit. However changing it now would break backwards compatibility which I don't want to do. It does look like the ambiguities you found are all in legacy parameters, so hopefully will not be too much of an issue going forward.
