### ISSUE TITLE
erlcloud_elb uses 2009-05-15

### ISSUE THREAD

**Issue by mikev** [gleber/erlcloud#166]
I'm seeing this issue:
http://stackoverflow.com/questions/11800472/add-a-vpc-node-to-elb-programmatically

My code is calling erlcloud_elb:register_instance.  An exception is thrown:

SQOR-0023:riak_archive mikev$ ./riak_archive add
escript: exception error: {aws_error,
                     {http_error,400,"Bad Request",
                         <<"<ErrorResponse xmlns=\"http://elasticloadbalancing.amazonaws.com/doc/2009-05-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>ELB in VPC"...>>}}
  in function  erlcloud_aws:aws_request/7 (src/erlcloud_aws.erl, line 55)
  in call from erlcloud_aws:aws_request_xml/5 (src/erlcloud_aws.erl, line 24)
  in call from erlcloud_elb:elb_simple_request/3 (src/erlcloud_elb.erl, line 142)
  in call from riak_archive:handle_add/0 (src/riak_archive.erl, line 270)
  in call from escript:run/2 (escript.erl, line 752)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1 
  in call from init:start_em/1 

The error appears to be related to erlcloud using the 2009-05-15 API rather than the newer API Version 2012-06-01.

**Comment by mikev** [comment]
Update.  I tested and tried changing the string from "2009-05-15" to "2012-06-01".  The function call then succeeded.  So indeed, this is the problem.

**Comment by ransomr** [comment]
Thanks. Could you please provide a PR to fix the issue?

**Comment by ransomr** [comment]
Thanks for the PR.
