### ISSUE TITLE
erlcloud_ddb2 does not validate query options correctly

### ISSUE THREAD

**Issue by motobob** [gleber/erlcloud#171]
https://github.com/gleber/erlcloud/blob/master/src/erlcloud_ddb2.erl#L589-L597
contradicts 
https://github.com/gleber/erlcloud/blob/master/src/erlcloud_ddb2.erl#L617

and fails:
```erlang
erlcloud_ddb2:q(SomeTable, SomeKeyCondition, [typed_record]).
** exception error: {erlcloud_ddb,{invalid_opt,{typed_record,true}}}
     in function  erlcloud_ddb2:verify_ddb_opt/2 (src/erlcloud_ddb2.erl, line 597)
     in call from erlcloud_ddb2:opt_folder/3 (src/erlcloud_ddb2.erl, line 610)
     in call from lists:foldl/3 (lists.erl, line 1248)
     in call from erlcloud_ddb2:q/4 (src/erlcloud_ddb2.erl, line 1791)
```

PR to fix that will come later on.

**Comment by zacharyfox** [comment]
You're calling it wrong, should be:

```erlang
erlcloud_ddb2:q(Table, KeyCondition, [{out, typed_record}]).
```

**Comment by motobob** [comment]
yes that works...need more docs:)

**Comment by ransomr** [comment]
Would be great to have a doc PR if you have the time to write up any of what you found missing. Thanks.

**Comment by smilerlee** [comment]
@ransomr I have been plaining to improve the source code self-documented ability, which means __some exported types could be changed or deleted__. This won't break any existing code however, just cause some dialyzer failures for who used these types explicitly (those code can still be compiled and run correctly).  I need to ask you for advise and permission before doing this, though.

eg:
* Prefix:
 * `in_expected_item()` -> `expected_item()`, `in_expected()` -> `expected()`
 * `in_update()` -> `attr_update()`, `in_updates()` -> `attr_updates()`
 * In general, the `in_` prefix is only apply to `in_attr_value()`, `in_attr()` and `in_item()` which has corresponding `out_` version
 * delete some rarely referenced `json_xxx()` types: `json_expected()`, `json_update()`, ... (not exported yet fortunately)

* Canonical names:
 * `return_value()` -> `return_values()`
 * `global_secondary_index_def()` -> `global_secondary_index()`, `local_secondary_index_def()` -> `local_secondary_index()` (no other type using `_def` suffix for now, and delete this suffix won't bring any ambiguities)

* Exports:
 * delete some type exports which should be internal: `boolean_opt()`, `maybe_list()`, `ok_return()`, ...
 * delete some type exports which is second-level or third-level and rarely referenced from outside: `update_action()`, `comparison_op()`, ...

* ...

**Comment by ransomr** [comment]
Those changes sound reasonable and I'm okay with changing a few exported types to improve clarity.
