### ISSUE TITLE
erlcloud_http:url_encode/1 does not support characters > 255

### ISSUE THREAD

**Issue by jasonwebster** [gleber/erlcloud#185]
I noticed this when trying to send an SNS payload where the message contents included a right single quote `’`, or character `8217`. Trying to encode a something that contains a character outside of the ascii plane, it will eventually raise an error when it gets to that character:

```
{function_clause,
    [{erlcloud_http,url_encode,
        [[8217,115,32 ....
```

Code in question is https://github.com/gleber/erlcloud/blob/master/src/erlcloud_http.erl#L34-L43

I'm not entirely sure what the best path forward is here. I checked `http_uri:encode/1` and it just passes through the characters un-encoded. I'd be happy to submit a PR after the correct way forward is decided upon.

**Comment by ransomr** [comment]
URIs don't support non-ASCII characters: https://tools.ietf.org/html/rfc3986#page-49. So there is a bug at a higher level that is causing this crash.

**Comment by jasonwebster** [comment]
Well, they do support them if they're hex percent encoded though. For example, my browser encodes a right single quote to `%E2%80%99`

**Comment by jasonwebster** [comment]
My question is then, should that be handled by `erlcloud_http:url_encode/1`?

**Comment by ransomr** [comment]
Yes, I think it should be handled. I'm assuming AWS will handle a percent encoding of the UTF-8 encoding of the character.

**Comment by jasonwebster** [comment]
I would hope so, but I'll be able to let you know shortly.

**Comment by motobob** [comment]
@jasonwebster i wonder this was tested on R16B03.
this is fails in ^ PR. Are we doing smth wrong
```erlang
module 'erlcloud_http'
  module 'erlcloud_http_tests'
    erlcloud_http_tests:6: url_encode_test_...*failed*
in function erlcloud_http_tests:'-url_encode_test_/0-fun-0-'/0 (test/erlcloud_http_tests.erl, line 6)
**error:{assertMatch_failed,[{module,erlcloud_http_tests},
                     {line,6},
                     {expression,"erlcloud_http : url_encode ( \"foo bar¡~!\" )"},
                     {pattern,"\"foo%20bar%C2%A1~%21\""},
                     {value,"foo%20bar%C3%82%C2%A1~%21"}]}
    erlcloud_http_tests:7: url_encode_test_...*failed*
in function erlcloud_http_tests:'-url_encode_test_/0-fun-2-'/0 (test/erlcloud_http_tests.erl, line 7)
**error:{assertMatch_failed,[{module,erlcloud_http_tests},
                     {line,7},
                     {expression,"erlcloud_http : url_encode ( \"�\\200\\230single quotes�\\200\\231\" )"},
                     {pattern,"\"%E2%80%98single%20quotes%E2%80%99\""},
                     {value,"%C3%A2%C2%80%C2%98single%20quotes%C3%A2%C2%80%C2%99"}]}
    erlcloud_http_tests:8: url_encode_test_...*failed*
in function erlcloud_http_tests:'-url_encode_test_/0-fun-4-'/0 (test/erlcloud_http_tests.erl, line 8)
**error:{assertMatch_failed,[{module,erlcloud_http_tests},
                     {line,8},
                     {expression,"erlcloud_http : url_encode ( \"¢\" )"},
                     {pattern,"\"%C2%A2\""},
                     {value,"%C3%82%C2%A2"}]}
    erlcloud_http_tests:9: url_encode_test_...*failed*
in function erlcloud_http_tests:'-url_encode_test_/0-fun-6-'/0 (test/erlcloud_http_tests.erl, line 9)
**error:{assertMatch_failed,[{module,erlcloud_http_tests},
                     {line,9},
                     {expression,"erlcloud_http : url_encode ( \"��\\201� ��\\201�\" )"},
                     {pattern,"\"%F0%A1%81%AF%20%F0%A1%81%B6\""},
                     {value,"%C3%B0%C2%A1%C2%81%C2%AF%20%C3%B0%C2%A1%C2%81%C2%B6"}]}
    [done in 0.011 s]
```

**Comment by jasonwebster** [comment]
No, it was only tested on 17 & 18.

**Comment by nalundgaard** [comment]
We are still on R16B03-1 for now for alertlogic. It would be lovely to understand why it's broken in the eunit tests. The output at the terminal in R16B03-1 *looks* right:

```sh
$ make run
erl -pa deps/*/ebin -pa ./ebin
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> erlcloud_http:url_encode("foo bar¡~!").
"foo%20bar%C2%A1~%21"
2> erlcloud_http:url_encode("‘single quotes’").
"%E2%80%98single%20quotes%E2%80%99"
3> erlcloud_http:url_encode("¢").
"%C2%A2"
4> erlcloud_http:url_encode("𡁯 𡁶").
"%F0%A1%81%AF%20%F0%A1%81%B6"
```

**Comment by ransomr** [comment]
Erlang 17.0 changed the default file encoding to UTF-8:
http://erlang.org/doc/apps/stdlib/unicode_usage.html

I wonder if the fix could be as simple as adding this to the top of the file:
`%% -*- coding: utf-8 -*-`

**Comment by nalundgaard** [comment]
@ransomr Totally right! I tested it here and it fixed it. #197 should resolve it. Thanks for the tip, I didn't realize you could specify encoding on the source file in that way.
