### ISSUE TITLE
DynamoDB Streams support

### ISSUE THREAD

**Issue by smilerlee** [gleber/erlcloud#189]
@ransomr  I'm working on DynamoDB Streams API implementation.

Very earlier preview code can be found [here](https://github.com/smilerlee/erlcloud/tree/ddb_streams_preview), the same style with `ddb2`. (errr, `erlcloud_ddb_streams_impl` is copied from `erlcloud_ddb_impl` for now, I'll rewrite it using `erlcloud_retry` later)

Though there're some details for simple output I need your help...

* [ListStreams](http://docs.aws.amazon.com/dynamodbstreams/latest/APIReference/API_ListStreams.html), simple output only contains `StreamArn`s

* [DescribeStream](http://docs.aws.amazon.com/dynamodbstreams/latest/APIReference/API_DescribeStream.html): maybe the `ShardId`s are enough for simple output, how do you think?

* [GetRecords](http://docs.aws.amazon.com/dynamodbstreams/latest/APIReference/API_GetRecords.html), there comes the toughest question: if the `StreamViewType` for a table is [`NEW_AND_OLD_IMAGES`](http://docs.aws.amazon.com/dynamodbstreams/latest/APIReference/API_StreamDescription.html#DDB-Type-StreamDescription-StreamViewType), the new and old images are both returned, should I just extract the `NewImage` for simple output? I'm hesitating on this actually...

Looking forward to your reply, and if you have any questions, please let me know.

**Comment by nalundgaard** [comment]
@smilerlee Wow, I have been working on this exact thing! I'll review your code tomorrow and I may make some adjustments to mine. A cursory glance shows that we did substantially the same thing, structurally.

Regarding your questions about simple output, I think leaving out huge parts of the response in `simple` mode is pretty silly. For my part, in my code's `simple` output I made a record_to_proplist converter for handling all the erlcloud_ddb_streams record types that converts (potentially nested) record output into nicely consumable proplists, and I use this for `simple` output. This then produces output like this:

```erlang
 erlcloud_ddb_streams:list_streams({limit, 1}]).
   {ok,[{last_evaluated_stream_arn,<<"arn:aws:dynamodb:us-wesst-2:111122223333:table/Forum/stream/2015-05-20T20:51:10.252">>},
        {streams,[[{stream_arn,<<"arn:aws:dynamodb:us-wesst-2:111122223333:table/Forum/stream/2015-05-20T20:51:10.252">>},
                   {stream_label,<<"2015-05-20T20:51:10.252">>},
                   {table_name,<<"Forum">>}]]}]}

 erlcloud_ddb_streams:describe_stream(<<"arn:aws:dynamodb:us-west-2:111122223333:table/Forum/stream/2015-05-20T20:51:10.252">>).
   {ok,[{creation_request_date_time, 1437677671.062},
        {key_schema, {<<"ForumName">>, <<"Subject">>}},
        {last_evaluated_shard_id, undefined},
        {shards,[[{parent_shard_id, <<"shardId-00000001414562045508-2bac9cd1">>},
                  {sequence_number_range, [{starting_sequence_number, <<"20500000000000000910398">>},
                                           {ending_sequence_number, <<"20500000000000000910398">>}]},
                  {shard_id, <<"shardId-00000001414562045508-2bac9cd2">>}]]},
        {stream_arn, <<"arn:aws:dynamodb:us-west-2:111122223333:table/Forum/stream/2015-05-20T20:51:10.252">>},
        {stream_label, <<"2015-05-20T20:51:10.252">>},
        {stream_status, enabled},
        {stream_view_type,new_and_old_images},
        {table_name,<<"Forum">>}]}
```

This strikes me as a very erlang-ish output style that is succinct, much less overhead than records madness, but doesn't omit data that's critical to using this API in any kind of real way, like `next_shard_iterator` in `get_records`, for example.

I don't have a working prototype ready—I am finishing up get_records now—but I'll publish it very soon.

**Comment by nalundgaard** [comment]
@smilerlee So, I think I got my version fully completed, with my proposed interface. Eunit Testing is still TODO. I've done some testing at the console, but I haven't tested the `get_records` function much yet. Curious what you guys think, if you have time to review.

**Comment by smilerlee** [comment]
@nalundgaard Wow, It's a kind of luck I suppose :D

It's pretty cool, we can learn from each other.

I've been looking into ddb streams for long, we would use its awesome features for log purpose and single item rolling back on our server, but it was a beta release all the time. I was so busy these days that I haven't focused on amazon releases for days. Fortunately it's not too late, I've already handled all the requests params in hours, and the json output worked fine.

I won't use proplists as simple output since they are not simple enough, but you inspired me that we could add `proplist` and `typed_proplist` as the fifth and sixth output format, or even `map`!

**Comment by nalundgaard** [comment]
@smilerlee fair enough about the proplists not being simple enough! Let me know if I can help. If you're happy with my record definitions, let's use them... I see you haven't really done that part for lots of the functions, based on looking at your branch?

We want to implement a backup solution internally at [alertlogic](https://github.com/alertlogic) as well, and my former colleague @holmosapien was working on this project until he left—right before streams went public, LOL. Anyway, I've taken over his task, and rewritten his work, which I think was patterned after another module in erlcloud, because it wasn't at all compatible with ddb2's perspective. I'll look forward to reviewing your code in more detail, and perhaps we can come to some mix that suits everyone.

**Comment by smilerlee** [comment]
@nalundgaard Quickly scanned your code, `erlcloud_ddb_streams_impl` is not necessary, you can use `erlcloud_retry` instead. Additionally, I'd prefer use `erlcloud_ddb2:stream_specification()` as output, rather than the `ddb2_stream_specification_description` record.
The remaining part is not that hard, I omitted them to come up a runnable code ASAP, and it did work, which surprised me!
I'll detailed review your code as soon as I finish most of this job.

**Comment by smilerlee** [comment]
@nalundgaard I found the module your former colleague's work patterned from, it's `erlcloud_kinesis`, another similar streams service from Amazon. There're some differences between these two services though.

I'll continue use the ddb2 style first, it's a DynamoDB derived service anyway; but I'll support both these two styles as most as possible later, make it friendly to kinesis users.

**Comment by nalundgaard** [comment]
@smilerlee to be honest, I don't care that much about either format. I am going to move our infrastructure to using `typed_record` output ASAP, so supporting the `erlcloud_kinesis` style or my proplist format is unnecessary. I don't think supporting the `erlcloud_kinesis` is needed.

**Comment by smilerlee** [comment]
@nalundgaard alright, thanks for your feedback, I'll reconsider that. Even though I would do that, it won't be that soon; completing current implementation and making it stable is most important of all.

**Comment by nalundgaard** [comment]
@smilerlee sounds good. I'm on this basically 100%. would it be alright to rectify my records work on top of your branch and make a PR to your branch? I'm trying to figure out how to make sure we can work together productively on this without wasting too much time & effort. :)

**Comment by smilerlee** [comment]
@nalundgaard I'm sorry but I don't know the exactly answer what the way it is to work together productively neither, since your code base is far apart from the upstream at a glance :(

My branch is temporary for now and I'll rebase and squash some of the commits together later. As soon as I finished, I'll let you know. Any improvement PRs would be welcome, and I think @ransomr would completely agree it. Actually, I'm just a contributor as you guys :)

**Comment by smilerlee** [comment]
The [smilerlee:ddb_streams_preview](https://github.com/smilerlee/erlcloud/tree/ddb_streams_preview) branch was updated and it worked correctly now, thanks @nalundgaard.

There are some known issues currently:
* the simple output for `get_records` is a list of `#ddb_streams_stream_record{}` for now, which isn't simple enough
* rename or clean up item related types
* delete `erlcloud_ddb_streams_impl.erl`
* add eunit tests
* code review and clean up
* ...

Except for the simple output for `get_records` needs to be settled, I'll complete other tasks later, maybe @nalundgaard you can give me a hand :)

This branch and so many commits are for dev & preview purpose only, the final PR will be squashed into two or more commits as needed.

**Comment by ransomr** [comment]
Thanks to both of you for working on this.

The intent of the `simple` returns was to make the records easier to work with for the callers by removing extra layers of wrapping. I'm not that familiar with the DynamoDB Streams API, but in the case of `get_records` I would expect it to just return a list of records. I would expect those records to contain all the information that is returned from the API - I don't think omitting information there would make the result easier to work with. This is simpler than the `{out,record}` version which would return an Erlang record with two fields: `next_shard_iterator` and `records`. Similarly for the other methods you asked about originally I would just maintain all the information that is returned for each stream.

**Comment by nalundgaard** [comment]
Thanks, @ransomr. @smilerlee I will get to the documentation now, since I had basically written it before. I'll have a PR for you in an hour or so, I think. Then I'll try to tackle the unit tests.

**Comment by smilerlee** [comment]
Thanks, @ransomr. I was over thought about the `simple` returns, I'll fix that.

**Comment by nalundgaard** [comment]
@smilerlee I added some documentation based on the API examples in the AWS Streams API Documentation, in smilerlee/erlcloud#2 as referenced above, which it seems you've found issues with and I think I've fixed them all. If that looks good, it seems like we have the basic interface agreed upon (for `simple`, `record`, `typed_record`, and `json` formats at least). I actually think the `json` format almost exactly matches that format that @holmosapien implemented when he used the `erlcloud_kinesis` pattern, so that takes care of that concern even though it's no big deal.

If you agree, I'll go ahead and get started on some eunit tests.

**Comment by smilerlee** [comment]
Thank you, @nalundgaard.
Of cause the `json` format is exactly the same whatever pattern you use, as long as using `jsx` for decoding.
Looking forward to your eunit tests.

**Comment by smilerlee** [comment]
And I'll go on with the underlying network refactoring.

**Comment by smilerlee** [comment]
Hi, @ransomr, I'd like to change [this line](https://github.com/gleber/erlcloud/blob/master/include/erlcloud_aws.hrl#L61) from `httpc_error_reason` to `error_reason` since it can be shared by both `aws` and `httpc` error types.

While implementing `result_fun` for `erlcloud_retry`, I need to decode the response body to determine whether should retry, I'd like to cache the decoded reason in the `#aws_request{}` for later return, instead of decoding the body again.

**Comment by ransomr** [comment]
What value do you want to store as the error_reason in the case of an aws error?

For the decoded body, I'm not completely following. Do you need to decode the body in the the result fun to determine if it is an error, or just to determine if an error should be retried? Do you want to share the decoded body between the result_fun and other internal code in erlcloud (which would then read and return it)? Or do you want to make it available to the retry_fun? Do you have a proposal for how you think it would make sense to implement this?

**Comment by smilerlee** [comment]
@ransomr It's hard to explain however. I've just pushed a new [commit](https://github.com/smilerlee/erlcloud/commit/02e307f481172f4080290de050cd60bfb8f783ec), you might want to have a look. The return format is identical to ddb2.

**Comment by smilerlee** [comment]
[This line](https://github.com/smilerlee/erlcloud/commit/02e307f481172f4080290de050cd60bfb8f783ec#diff-e6a9457dd0cdc3e24146902330913ce0R844) and [this line](https://github.com/smilerlee/erlcloud/commit/02e307f481172f4080290de050cd60bfb8f783ec#diff-e6a9457dd0cdc3e24146902330913ce0R847) are what I need to store in the error_reason for later usage
