### ISSUE TITLE
Unable to list s3 buckets 'SignatureDoesNotMatch'

### ISSUE THREAD

**Issue by JoshRagem** [gleber/erlcloud#192]
I'm constantly getting `SignatureDoesNotMatch` error response from s3.

Here is part of the response from s3:

```
<StringToSign>GET\n\n\nWed, 29 Jul 2015 15:46:05 GMT\n/s3.us-west-2.amazonaws.com/</StringToSign>
<SignatureProvided>cR/Y+/DNerdlsTuMlapkx5wm+VQ=</SignatureProvided>
```

but when I attempt ` base64:encode(erlcloud_util:sha_mac(SecretKey, StringToSign))` myself, the signature I get is: `sKK1Vzpa/JDcA2dpPzq0fuoeb9A`

**Comment by ransomr** [comment]
I'm not aware of any implementation issues that would cause this. Verify that your security credentials (key id and secret key) match. If you are trying to use temporary credentials, check that you are using the temporary credentials for both fields as well as providing the security token.

If that is all correct, then check the string to sign that erlcloud is computing. Does it match the one in the error response?

**Comment by JoshRagem** [comment]
Using the debugger I find that the string erlcloud_s3 generates to sign is: `GET\n\n\nWed, 29 Jul 2015 15:46:05 GMT\n/` where the host is hard coded to '"/"` on line 299

This string does not match the one amazon is reporting back.

**Comment by ransomr** [comment]
Thanks. Took a quick look and this is probably a bug in ListBuckets. That is the only method that doesn't take a bucket name. According to the doc http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html the string to sign is correct for a ListAllBuckets request. Maybe the bug then is that erlcloud is making the request incorrectly - putting the host in where there should be none. I'm assuming that you can make other s3 requests successfully, in which case it seems likely that the bug is in the ListAllBuckets implementation.

**Comment by JoshRagem** [comment]
Thanks for the response, 

I actually came on this bug because I was unable to `put_object` and I wanted to test something more basic; so my problems are not limited to just list buckets.

**Comment by ransomr** [comment]
Ok. I've verified that `list_buckets` does work correctly for me, so the problem must be with how you are configured. What is your config?

**Comment by JoshRagem** [comment]
I have other projects that use erlcloud for sqs and kinesis, so I really just did a copy paste from those to get:

```
Config = #aws_config{
                access_key_id=os:getenv("AWS_ACCESS_KEY_ID"),
                secret_access_key=os:getenv("AWS_SECRET_ACCESS_KEY"),
                s3_host = os:getenv("AWS_S3_HOST")
}.
```

... but I just tried again without defining `s3_host` and that fixed everything. I guess that means I should not set s3 host :)

**Comment by motobob** [comment]
@JoshRagem yes, you should not set s3_host unless your bucket is in non default region.

**Comment by JoshRagem** [comment]
@motobob the bucket is in `us-west-2` which is, I believe, a non default region.

**Comment by motobob** [comment]
so AWS_S3_HOST should be `s3-us-west-2.amazonaws.com` then not "s3<b>.</b>us-west-2.amazonaws.com"
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by JoshRagem** [comment]
Thank you for the clarification. I didn't realize that s3 didn't follow the same pattern as sqs and kinesis.
