### ISSUE TITLE
hackney as a configurable http client fails with at least the erlcloud_ddb2 module

### ISSUE THREAD

**Issue by okeuday** [gleber/erlcloud#205]
Issue to track the failure based on the changes/comments in https://github.com/gleber/erlcloud/pull/183.  The steps to reproduce the problem are at https://gist.github.com/okeuday/c72d4f346ee0d83d8b5f (it requires replacing INVALID with the proper keys).  Used Erlang/OTP 18.0 with hackney 1.3.2.

**Comment by okeuday** [comment]
@hemantkr @benoitc moved the hackney error here

**Comment by benoitc** [comment]
I will try the complete source code later in the afternoon (need to access to my AWS account ;) . Anyway I just did a direct test to the url without the credentials and got the following:

```erlang
1> application:ensure_all_started(hackney).
{ok,[crypto,asn1,public_key,ssl,idna,mimerl,certifi,
     hackney]}
2> hackney:get("https://dynamodb.us-west-2.amazonaws.com").
{ok,200,
    [{<<"x-amzn-RequestId">>,
      <<"07RIK1R3QPH8DLDJA54AVP09JVVV4KQNSO5AEMVJF66Q9ASUAAJG">>},
     {<<"x-amz-crc32">>,<<"1920725165">>},
     {<<"Content-Length">>,<<"42">>},
     {<<"Date">>,<<"Sun, 13 Sep 2015 10:00:04 GMT">>}],
    #Ref<0.0.4.67>}
```

It seems to work there. Can you tell me the result you have? Can you try with the latest master?

**Comment by okeuday** [comment]
@benoitc Whatever the reason for the error, it no longer occurs.  I have tested both with 1.3.2 and master of hackney, both work on my own development machine and an ec2 instance, so everything is fine now.  I am not sure why it was failing before, but it shouldn't be due to erlcloud or hackney.  Thanks!
