### ISSUE TITLE
Merging alertlogic fork into upstream

### ISSUE THREAD

**Issue by motobob** [gleber/erlcloud#209]
Hello @ransomr  
I would really like fix the past problem of our fork being significantly diverged from the upstream while having quite a lot of good features needed in the upstream either.
I'm talking about submitting a PR from: https://github.com/gleber/erlcloud/compare/master...alertlogic:master.
Would you be okay reviewing such a big PR? I'm not sure how to split it into just several ones while keeping the feature set not broken,

As you may notice it has a major differences as here is a brief overview:
- Full support for SigV4 across all modules. According to AWS, all services support SigV4 in all regions and only a few still have SigV2 therefore SigV2 funs were not removed if smb still needs them 
- S3 follow redirect option was added
- KMS update, basically reworked #182
- DirectConnect described APIs added
- RDS APIs added 
- Route53 added
- Enabling travis CI builds for PRs. To enable it for you, permission should be set correctly
- `erlcloud_autoscalling` added along with some edits `erlcloud_as` to have backward compatibility
- Large number of maintenance defect fixes here and there
- enhancements to  DDB2, EC2 (adding all the gateways)  and Kinesis
- enriching ELB APIs
- adding more testing

**Comment by smilerlee** [comment]
@motobob Wow! What a big PR!

How about...
* create a new branch from `gleber/master` (let's call it `A`), and...
* reproduce features one by one on this newly created branch `A` (this can be archived by checkout `master`, reset to `A` with `--mixed`, then commit hunks by hunks), and...
* revert unnecessary changes on your local `master`...
* finally branch `A` and your local `master` will become identical
* push `master` to `alertlogic/master`, push `A` to upstream
* after merging `A`, you'll be able to merge upstream changes I suppose.

Maybe you can make some tests.

**Comment by ransomr** [comment]
Wow - took a quick look and there's a ton of good stuff there. I'd love to get this merged, so while I'd much prefer smaller PRs going forward, I'm willing to take this as one large PR. Please open it from a branch that isn't going to change while I'm reviewing it though - might take me a while to get through it all.

**Comment by motobob** [comment]
@ransomr @smilerlee thank you for feedback.
Let me do the following:
- i'll pin our master to some branch and open the "master" PR to keep track of it.
- i'll open several small PRs for auxiliary things and where completely new module was added. That will minimize the delta of the "master PR". I doubt i'll be able two major features Sigv4 and S3 redirect, but at least that will simplify reviewing. 

hope that works with you

**Comment by smilerlee** [comment]
@motobob As I see the `dynamize_expression/1` function in `erlcloud_ddb2`, I suggest deleting all the list or tuple stuffs if your production code is not using them, since it add more complexity rather than convenience:
* `KeyConditionsOrExpression` arg in `q` and `UpdatesOrExpression` arg in `update_item` would treat list or tuple as `condition()`/`in_updates()`, not `expression()`;
* The tuple format is not that in agreement with the existing code.

I had thought adding other format rather than binaries when implementing expression functions, but I chose not doing that at last.
In my opinion, the binary format is much simpler and more flexible.

You might want to take a look at my unfinished work:
```Erlang
-type projection_expression() :: binary() |
                                 {projection, [binary(),...]}.

%% Condition Expression Reference
%% [http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html#ConditionExpressionReference]
-type condition_expression() :: binary() |
                                {eq, binary(), binary()} |
                                {ne, binary(), binary()} |
                                {lt, binary(), binary()} |
                                {le, binary(), binary()} |
                                {gt, binary(), binary()} |
                                {ge, binary(), binary()} |
                                {between, binary(), binary(), binary()} |
                                {in, binary(), [binary(),...]} |
                                {attribute_exists , binary()} |
                                {attribute_not_exists, binary()} |
                                {attribute_type, binary(), binary()} | %% we cannot use `attr_type()` here, see the reference
                                {begins_with, binary(), binary()} |
                                {contains, binary(), binary()} |
                                {size, binary()} | %% TODO `size (path)` can be an operand for eq, lt, etc.
                                {'and', condition_expression(), condition_expression()} |
                                {'or', condition_expression(), condition_expression()} |
                                {'not', condition_expression()}.

-type filter_expression() :: condition_expression().

-type update_expression() :: binary() |
                             maybe_list(update_expression_section()).
-type update_expression_section() :: binary() |
                                     update_expression_set() |
                                     update_expression_remove() |
                                     update_expression_add() |
                                     update_expression_delete().
-type update_expression_set() :: {set, maybe_list({binary(), binary() |
                                                         {plus, binary(), binary()} |
                                                         {minus, binary(), binary()} |
                                                         {if_not_exists, binary(), binary()} |
                                                         {list_append, binary(), binary()}
                                              })}.
-type update_expression_remove() :: {remove, maybe_list(binary())}.
-type update_expression_add() :: {add, maybe_list({binary(), binary() | number()})}.
-type update_expression_delete() :: {delete, binary(), binary()}.
```
It's so complex that I didn't continue it.

**Comment by motobob** [comment]
@smilerlee I would agree that this particular `erlcloud_ddb2` change could be done differently. i'm not comfortable taking in unfinished work so please feel free so submit a PR when done.

**Comment by motobob** [comment]
@ransomr i'm closing this one to continue the discussion within #215.
