### ISSUE TITLE
Update Hex.pm package

### ISSUE THREAD

**Issue by waisbrot** [gleber/erlcloud#220]
Erlcloud is still at 0.9.2 on Hex. It'd be great to have newer versions available there.

**Comment by gleber** [comment]
@ransomr I'll gladly give you whatever access needed to do this one. I am way out of the loop at this moment...

**Comment by ransomr** [comment]
@waisbrot I don't use Hex, but the version is Hex is community managed. I think you can submit a PR to this file to update it: https://github.com/hexpm/community/blob/master/packages/erlcloud.exs.

**Comment by waisbrot** [comment]
I checked with the Hex community project and they're discontinuing community management. I now have publish permissions to Erlcloud on Hex and I've pushed 0.11.0 and 0.12.0.

I'm an active user of Erlcloud and am happy to handle Hex packaging, but I will give away the publisher powers if there's anyone else that you'd rather have.

**Comment by ransomr** [comment]
Thank you very much, glad you are willing to do it.
